@startuml
actor Apprenant
actor Formateur

usecase "Répondre au QCM" as UC1
usecase "Créer et publier un QCM" as UC4
usecase "Voir les résultats" as UC2

Apprenant -down-- UC1
Apprenant -down-- UC2

Formateur -down-- UC4
@enduml
