@startuml
actor Formateur

usecase "Consulter les résultats des apprenants" as UC6
usecase "Analyser les statistiques" as UC7
usecase "Gérer les questions" as UC8

Formateur -down-- UC6
Formateur -down-- UC7
Formateur -down-- UC8
@enduml